/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExpenseEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'sheet' : IDL.Text,
  'notes' : IDL.Text,
  'companyName' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([IDL.Text], [], []),
  'addExpenseEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
      [ExpenseEntry],
      [],
    ),
  'deleteExpenseEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllEntries' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
  'getEntriesForSheet' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExpenseEntry)],
      ['query'],
    ),
  'updateExpenseEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExpenseEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'sheet' : IDL.Text,
    'notes' : IDL.Text,
    'companyName' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([IDL.Text], [], []),
    'addExpenseEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Int,
        ],
        [ExpenseEntry],
        [],
      ),
    'deleteExpenseEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllEntries' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
    'getEntriesForSheet' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExpenseEntry)],
        ['query'],
      ),
    'updateExpenseEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };