/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExpenseEntry {
  'id' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'sheet' : string,
  'notes' : string,
  'companyName' : string,
  'category' : string,
  'amount' : number,
}
export interface _SERVICE {
  'addCategory' : ActorMethod<[string], undefined>,
  'addExpenseEntry' : ActorMethod<
    [string, string, string, string, number, string, bigint],
    ExpenseEntry
  >,
  'deleteExpenseEntry' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllEntries' : ActorMethod<[], Array<ExpenseEntry>>,
  'getEntriesForSheet' : ActorMethod<[string], Array<ExpenseEntry>>,
  'updateExpenseEntry' : ActorMethod<
    [bigint, string, string, string, string, number, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];